version: '3.3'
services:
    webappgallery_client:
        build:
            context: ./packages/client/
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
    webappgallery_server:
        build:
            context: ./packages/server/
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
    mongo:
        image: mongo
        restart: always
        volumes:
            - /data/db
